
version: 0.2


phases:
  install:
    commands:
      - echo Installing npm dependencies
      - apt-get update -y
      - apt-get install -y node
      - apt-get install -y npm
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - sh ./Scripts/test.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

